"""Emitted RTL: snapshots, plus the invariants a snapshot cannot express.

Snapshots catch *unintended* change. They cannot tell a good diff from a bad
one, so the checks below assert the things that must hold no matter how the
template is reformatted -- the slice expressions agree with the IR, every field
reaches a port, and nothing that must not appear in generated text does.

Regenerate after an intentional template change:

    WIRESPEC_UPDATE_SNAPSHOTS=1 python3 -m pytest tests/test_emit.py
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

import pytest

from wirespec.emit import make_env, render, slice_expr, write
from wirespec.ir import Segment
from wirespec.layout import build_layout

from .conftest import ROOT

SNAP_DIR = Path(__file__).resolve().parent / "snapshots"
UPDATE = os.environ.get("WIRESPEC_UPDATE_SNAPSHOTS") == "1"


@pytest.fixture(scope="module")
def files(eth_ir):
    return render(build_layout(eth_ir, 64), out_dir="rtl/generated")


@pytest.fixture(scope="module")
def feed_files(feed_ir):
    return render(build_layout(feed_ir, 64), out_dir="rtl/generated")


def test_framed_snapshots_match(feed_files):
    SNAP_DIR.mkdir(exist_ok=True)
    stale = []
    for f in feed_files:
        snap = SNAP_DIR / f.path.name
        if UPDATE or not snap.exists():
            snap.write_text(f.text, encoding="utf-8")
            continue
        if snap.read_text(encoding="utf-8") != f.text:
            stale.append(f.path.name)
    if UPDATE:
        pytest.skip("snapshots rewritten")
    assert not stale, f"emitted RTL differs from the snapshot for {stale}"


def test_field_extract_needs_no_muxes_for_simple_feed(feed_files, feed_ir):
    """Every simple_feed field sits at one offset, so every slice is static.

    A mux would appear as an always_comb block. Their absence is the concrete
    payoff of rotating the window before slicing it.
    """
    text_ = next(f.text for f in feed_files if "field_extract" in f.path.name)
    layout = build_layout(feed_ir, 64)
    assert all(f.uniform for f in layout.msg_fields)
    assert "always_comb" not in text_, "a field needed a mux over message types"
    for f in layout.msg_fields:
        m = re.search(rf"^  assign {re.escape(f.sig)}\s+= (.+);$", text_, re.M)
        assert m, f"no assign for {f.name}"
        assert m.group(1) == slice_expr("i_win", f.segments)
        assert f"o_rec[{f.rec_lsb:<4} +:" in text_ or f"o_rec[{f.rec_lsb} +:" in text_


def test_field_extract_checks_every_declared_size(feed_files, feed_ir):
    text_ = next(f.text for f in feed_files if "field_extract" in f.path.name)
    for m in build_layout(feed_ir, 64).messages:
        assert f"(is_{m.name} && (i_total == TOT_W'({m.bytes_})))" in text_


def test_framed_top_registers_the_message_bus(feed_files):
    """B006: the message bus must sit on the same stage as the packet verdict."""
    text_ = next(f.text for f in feed_files if f.path.name.startswith("parser_top"))
    assert "msg_valid_q <= fr_slot_valid;" in text_
    assert "assign o_msg_valid = msg_valid_q;" in text_


# --------------------------------------------------------------------------
# Snapshots
# --------------------------------------------------------------------------


def test_three_files_are_emitted(files):
    assert [f.path.name for f in files] == [
        "eth_ipv4_udp_pkg.sv",
        "hdr_parse_eth_ipv4_udp.sv",
        "parser_top_eth_ipv4_udp.sv",
    ]


def test_snapshots_match(files):
    SNAP_DIR.mkdir(exist_ok=True)
    stale = []
    for f in files:
        snap = SNAP_DIR / f.path.name
        if UPDATE or not snap.exists():
            snap.write_text(f.text, encoding="utf-8")
            continue
        if snap.read_text(encoding="utf-8") != f.text:
            stale.append(f.path.name)
    if UPDATE:
        pytest.skip("snapshots rewritten")
    assert not stale, (
        f"emitted RTL differs from the snapshot for {stale}. If that was intended, "
        f"rerun with WIRESPEC_UPDATE_SNAPSHOTS=1 and review the diff in git."
    )


# --------------------------------------------------------------------------
# Invariants of the generated text
# --------------------------------------------------------------------------


def text(files, name: str) -> str:
    return next(f.text for f in files if f.path.name == name)


def test_generated_files_say_they_are_generated(files):
    for f in files:
        assert "GENERATED by wirespec" in f.text
        assert "do not edit" in f.text
        assert "wirespec gen --schema" in f.text, "the banner must say how to regenerate"


def test_no_placeholder_or_unrendered_syntax(files):
    for f in files:
        assert "{{" not in f.text and "{%" not in f.text, f"{f.path.name} has unrendered Jinja"
        assert "TODO" not in f.text and "FIXME" not in f.text
        assert "None" not in f.text, f"{f.path.name} leaked a Python None"


def test_every_field_reaches_a_port(files, eth_ir):
    parse = text(files, "hdr_parse_eth_ipv4_udp.sv")
    top = text(files, "parser_top_eth_ipv4_udp.sv")
    layout = build_layout(eth_ir, 64)
    for f in layout.all_fields:
        assert re.search(rf"\b{f.port}\b", parse), f"{f.port} missing from hdr_parse"
        assert re.search(rf"\b{f.port}\b", top), f"{f.port} missing from parser_top"


def test_slices_in_the_text_agree_with_the_ir(files, eth_ir):
    """Read the emitted assigns back and check them against the IR, not by eye."""
    parse = text(files, "hdr_parse_eth_ipv4_udp.sv")
    layout = build_layout(eth_ir, 64)
    checked = 0
    for lay in layout.layers:
        for f in lay.fields:
            m = re.search(rf"^  assign {re.escape(f.sig)}\s+= (.+);$", parse, re.M)
            assert m, f"no assign for {lay.name}.{f.name}"
            got = m.group(1)
            want = slice_expr(f"win_{lay.name}", f.ir.segments)
            assert got == want, f"{lay.name}.{f.name}: emitted {got}, IR says {want}"
            checked += 1
    assert checked == 20


def test_one_shift_per_dynamic_layer_and_none_per_field(files, eth_ir):
    """The whole point of rotate-then-slice: shifters scale with layers, not fields."""
    parse = text(files, "hdr_parse_eth_ipv4_udp.sv")
    layout = build_layout(eth_ir, 64)
    dynamic = [lay for lay in layout.layers if lay.dynamic]
    assert [lay.name for lay in dynamic] == ["udp"]
    shifts = re.findall(r"assign win_\w+ = i_win\[sh_\w+ \+:", parse)
    assert len(shifts) == len(dynamic) == 1, (
        f"{len(shifts)} run-time shifts for {len(dynamic)} dynamic layer(s); "
        f"a shift per field would be {sum(len(lay.fields) for lay in dynamic)}"
    )


def test_static_layers_use_constant_slices(files):
    parse = text(files, "hdr_parse_eth_ipv4_udp.sv")
    assert "assign win_eth = i_win[0 +: 112];" in parse
    assert "assign win_ipv4 = i_win[112 +: 160];" in parse


def test_internal_signals_are_layer_qualified(files, eth_ir):
    """Two layers may carry a field of the same name; the signals must not collide."""
    parse = text(files, "hdr_parse_eth_ipv4_udp.sv")
    layout = build_layout(eth_ir, 64)
    sigs = [f.sig for f in layout.all_fields]
    assert len(set(sigs)) == len(sigs)
    assert "ipv4_hdr_checksum" in sigs and "udp_checksum" in sigs
    for s in sigs:
        assert re.search(rf"^  assign {re.escape(s)}\s+=", parse, re.M)
    # A bare `checksum` or `length` would be ambiguous across layers.
    assert not re.search(r"^  assign (checksum|length|version)\s+=", parse, re.M)


def test_error_precedence_matches_the_model(files):
    """Per layer: fixed-size, then length bounds, then declared-length truncation."""
    parse = text(files, "hdr_parse_eth_ipv4_udp.sv")
    order = re.findall(r"\((?:active_)(\w+) && (trunc_fix|len_bad|trunc_len)_\w+\)", parse)
    assert order == [
        ("eth", "trunc_fix"),
        ("ipv4", "trunc_fix"),
        ("ipv4", "len_bad"),
        ("ipv4", "trunc_len"),
        ("udp", "trunc_fix"),
    ]


def test_package_carries_offsets_and_enums(files):
    pkg = text(files, "eth_ipv4_udp_pkg.sv")
    assert "localparam int ETH_IPV4_UDP_HDR_BYTES = 82;" in pkg
    assert "ETHERTYPE_E_IPV4 = 16'h0800" in pkg
    assert "IP_PROTO_E_UDP   = 8'h11" in pkg or "IP_PROTO_E_UDP = 8'h11" in pkg
    assert "IPV4_FRAG_OFFSET_OFF" in pkg
    assert "LAYER_UDP" in pkg


def test_data_w_changes_only_the_default(eth_ir):
    """HDR_BYTES is a protocol property; DATA_W must not move any field."""
    def body(f):
        # Drop the banner: it names the width it was generated at, by design.
        return f.text.split("// ----", 3)[-1]

    a = render(build_layout(eth_ir, 64))
    b = render(build_layout(eth_ir, 128))
    for fa, fb in zip(a, b, strict=True):
        if fa.path.name == "parser_top_eth_ipv4_udp.sv":
            # The only difference is the DATA_W parameter default, which the
            # build overrides anyway.
            assert body(fa).replace("DATA_W = 64", "DATA_W = 128") == body(fb)
            continue
        assert body(fa) == body(fb), fa.path.name


# --------------------------------------------------------------------------
# Writing and the CLI
# --------------------------------------------------------------------------


def test_checked_in_sample_is_current(files):
    """rtl/generated/ is gitignored except this sample, so it must not go stale.

    Refresh with `make gen-sample`.
    """
    sample = ROOT / "rtl" / "generated" / "sample"
    if not sample.exists():
        pytest.skip("no checked-in sample; run `make gen-sample`")
    for f in files:
        got = sample / f.path.name
        assert got.exists(), f"{got} is missing from the checked-in sample"
        want = f.text.replace("--out rtl/generated", "--out rtl/generated/sample")
        assert got.read_text(encoding="utf-8") == want, (
            f"{f.path.name} in rtl/generated/sample/ is out of date; run `make gen-sample`"
        )


def test_write_creates_the_tree(files, tmp_path):
    written = write(files, root=tmp_path)
    assert len(written) == 3
    for p in written:
        assert p.exists() and p.read_text(encoding="utf-8")


def test_templates_use_strict_undefined():
    """A typo'd variable in a template must fail loudly, not render as blank."""
    env = make_env()
    t = env.from_string("{{ nope }}")
    with pytest.raises(Exception):
        t.render()


def test_slice_expr_shapes():
    assert slice_expr("w", (Segment(7, 0),)) == "w[7:0]"
    assert slice_expr("w", (Segment(23, 16), Segment(31, 24))) == "{w[23:16], w[31:24]}"


def test_cli_gen_writes_files(tmp_path):
    out = subprocess.run(
        [
            sys.executable,
            "-m",
            "wirespec.cli",
            "gen",
            "--schema",
            str(ROOT / "schemas" / "eth_ipv4_udp.yaml"),
            "--data-w",
            "128",
            "--out",
            "gen",
            "--root",
            str(tmp_path),
        ],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    assert out.returncode == 0, out.stderr
    assert (tmp_path / "gen" / "parser_top_eth_ipv4_udp.sv").exists()
    assert "header window 82 B" in out.stdout


def test_cli_reports_a_bad_schema_without_a_traceback(tmp_path):
    out = subprocess.run(
        [
            sys.executable,
            "-m",
            "wirespec.cli",
            "gen",
            "--schema",
            str(ROOT / "schemas" / "invalid" / "dup_field.yaml"),
        ],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    assert out.returncode == 2
    assert "duplicate field name" in out.stderr
    assert "Traceback" not in out.stderr


def test_cli_generates_a_framed_schema(tmp_path):
    out = subprocess.run(
        [
            sys.executable,
            "-m",
            "wirespec.cli",
            "gen",
            "--schema",
            str(ROOT / "schemas" / "simple_feed.yaml"),
            "--out",
            "gen",
            "--root",
            str(tmp_path),
        ],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    assert out.returncode == 0, out.stderr
    for name in (
        "simple_feed_pkg.sv",
        "hdr_parse_simple_feed.sv",
        "field_extract_simple_feed.sv",
        "parser_top_simple_feed.sv",
    ):
        assert (tmp_path / "gen" / name).exists(), name
