"""Render a Layout into SystemVerilog.

The templates do formatting; every number they print was computed in
``layout.py`` or ``ir.py``. That split is what lets the snapshot tests be a check
on the *text* rather than a second implementation of the arithmetic.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined

from .ir import Segment
from .layout import FieldLayout, Layout, LayerLayout

TEMPLATE_DIR = Path(__file__).resolve().parent / "templates"

BANNER = """\
// -----------------------------------------------------------------------------
// GENERATED by wirespec {version} -- do not edit.
//
//   schema : {schema}
//   DATA_W : {data_w}
//
// Edit the template (wirespec/templates/{template}) and re-run:
//   wirespec gen --schema {schema} --data-w {data_w} --out {out}
// -----------------------------------------------------------------------------
"""


def slice_expr(win: str, segments: tuple[Segment, ...]) -> str:
    """A field value as a concatenation of static slices of its window."""
    parts = [f"{win}[{s.msb}:{s.lsb}]" for s in segments]
    if len(parts) == 1:
        return parts[0]
    return "{" + ", ".join(parts) + "}"


def sv_int(value: int, width: int) -> str:
    return f"{width}'h{value:0{(width + 3) // 4}x}"


def pad(text: str, width: int) -> str:
    return text.ljust(width)


@dataclass(frozen=True)
class EmittedFile:
    path: Path
    text: str

    @property
    def lines(self) -> int:
        return self.text.count("\n")


def f_port(layout: Layout, field_name: str) -> str:
    """The output port carrying a named field of the packet header."""
    for f in layout.layers[0].fields:
        if f.name == field_name:
            return f.port
    raise KeyError(f"{field_name} is not a field of {layout.layers[0].name}")


def make_env() -> Environment:
    env = Environment(
        loader=FileSystemLoader(str(TEMPLATE_DIR)),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    env.globals.update(
        slice_expr=slice_expr, sv_int=sv_int, pad=pad, f_port=f_port, max=max, len=len
    )
    return env


def _banner(layout: Layout, template: str, out: str) -> str:
    from . import __version__

    return BANNER.format(
        version=__version__,
        schema=layout.name,
        data_w=layout.data_w,
        template=template,
        out=out,
    )


#: template -> output filename, per schema kind.
#:
#: A framed packet header is a layer chain of length one, so both kinds share
#: hdr_parse_layered.sv.j2 rather than having a near-duplicate template.
LAYERED_FILES = {
    "proto_pkg.sv.j2": "{name}_pkg.sv",
    "hdr_parse_layered.sv.j2": "hdr_parse_{name}.sv",
    "parser_top_layered.sv.j2": "parser_top_{name}.sv",
}

FRAMED_FILES = {
    "proto_pkg.sv.j2": "{name}_pkg.sv",
    "hdr_parse_layered.sv.j2": "hdr_parse_{name}.sv",
    "field_extract.sv.j2": "field_extract_{name}.sv",
    "msg_check.sv.j2": "msg_check_{name}.sv",
    "parser_top_framed.sv.j2": "parser_top_{name}.sv",
}


def render(layout: Layout, *, out_dir: str = "rtl/generated") -> list[EmittedFile]:
    """Render every file for ``layout``. Nothing is written to disk here."""
    env = make_env()
    files: list[EmittedFile] = []
    plan = FRAMED_FILES if layout.framed else LAYERED_FILES
    for template_name, pattern in plan.items():
        template = env.get_template(template_name)
        text = template.render(
            L=layout,
            layers=layout.layers,
            banner=_banner(layout, template_name, out_dir),
        )
        files.append(EmittedFile(Path(out_dir) / pattern.format(name=layout.name), text))
    return files


def write(files: list[EmittedFile], root: Path | str = ".") -> list[Path]:
    """Write rendered files, creating directories as needed."""
    root = Path(root)
    written = []
    for f in files:
        target = root / f.path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(f.text, encoding="utf-8")
        written.append(target)
    return written


__all__ = [
    "EmittedFile",
    "FieldLayout",
    "LayerLayout",
    "render",
    "slice_expr",
    "write",
]
