// -----------------------------------------------------------------------------
// GENERATED by wirespec 0.1.0 -- do not edit.
//
//   schema : simple_feed
//   DATA_W : 64
//
// Edit the template (wirespec/templates/field_extract.sv.j2) and re-run:
//   wirespec gen --schema simple_feed --data-w 64 --out rtl/generated
// -----------------------------------------------------------------------------

// Static field extraction from one rotated message window.
//
// msg_rotate has already put the message's first byte at bit 0, so every field
// here is a constant bit slice -- no lane muxing, no dependence on where the
// message happened to start in the beat. That is the whole point of rotating
// first: this module is instantiated once per message *slot*, and its cost does
// not grow with the number of fields.
//
// A field carried by several message types at the same offset is one slice
// shared between them. Only a field that sits at *different* offsets in
// different types needs a mux, and then it is a mux over the handful of type
// codes, never over the lanes of a beat.
//
// 18 record fields across 4 message types; 0 need a mux.
//
// Combinational.

`timescale 1ns / 1ps
`default_nettype none

module field_extract_simple_feed #(
  parameter int MSG_BITS = simple_feed_pkg::SIMPLE_FEED_MSG_MAX * 8,
  parameter int TOT_W    = 18,
  parameter int REC_W    = simple_feed_pkg::SIMPLE_FEED_REC_W
) (
  input  wire [MSG_BITS-1:0] i_win,    // byte 0 = start of the message
  input  wire [TOT_W-1:0]    i_total,  // total bytes the length prefix declares

  output wire                o_type_ok,
  output wire                o_size_ok,
  output wire [7:0]          o_type,
  output wire [REC_W-1:0]    o_rec
);

  // ------------------------------------------------------- discrimination --
  assign o_type = i_win[23:16];

  logic is_trade;
  logic is_quote;
  logic is_status;
  logic is_imbalance;

  assign is_trade        = (o_type == 8'h01);
  assign is_quote        = (o_type == 8'h02);
  assign is_status       = (o_type == 8'h03);
  assign is_imbalance    = (o_type == 8'h04);

  assign o_type_ok = is_trade || is_quote || is_status || is_imbalance;

  // Every type has a fixed size, so the length prefix is redundant -- and
  // therefore checkable. A length that disagrees with the type is malformed.
  assign o_size_ok = (is_trade && (i_total == TOT_W'(25))) ||
                     (is_quote && (i_total == TOT_W'(23))) ||
                     (is_status && (i_total == TOT_W'(14))) ||
                     (is_imbalance && (i_total == TOT_W'(32)));

  // ---------------------------------------------------------------- fields --
  logic [15:0]         f_msg_len         ;  // 16b, in trade, quote, status, imbalance
  logic [7:0]          f_msg_type        ;  // 8b, in trade, quote, status, imbalance
  logic [63:0]         f_symbol          ;  // 64b, in trade, quote, imbalance
  logic signed [63:0]  f_price           ;  // 64b signed, in trade
  logic [31:0]         f_qty             ;  // 32b, in trade
  logic [7:0]          f_side            ;  // 8b, in trade
  logic [7:0]          f_trade_flags     ;  // 8b, in trade
  logic signed [31:0]  f_bid_px          ;  // 32b signed, in quote
  logic signed [31:0]  f_ask_px          ;  // 32b signed, in quote
  logic [15:0]         f_bid_sz          ;  // 16b, in quote
  logic [15:0]         f_ask_sz          ;  // 16b, in quote
  logic [7:0]          f_session_state   ;  // 8b, in status
  logic signed [15:0]  f_reason_code     ;  // 16b signed, in status
  logic [63:0]         f_timestamp       ;  // 64b, in status
  logic [63:0]         f_paired_qty      ;  // 64b, in imbalance
  logic signed [63:0]  f_imbalance_qty   ;  // 64b signed, in imbalance
  logic signed [31:0]  f_ref_px          ;  // 32b signed, in imbalance
  logic [7:0]          f_auction_type    ;  // 8b, in imbalance

  assign f_msg_len          = {i_win[7:0], i_win[15:8]};
  assign f_msg_type         = i_win[23:16];
  assign f_symbol           = {i_win[31:24], i_win[39:32], i_win[47:40], i_win[55:48], i_win[63:56], i_win[71:64], i_win[79:72], i_win[87:80]};
  assign f_price            = {i_win[95:88], i_win[103:96], i_win[111:104], i_win[119:112], i_win[127:120], i_win[135:128], i_win[143:136], i_win[151:144]};
  assign f_qty              = {i_win[159:152], i_win[167:160], i_win[175:168], i_win[183:176]};
  assign f_side             = i_win[191:184];
  assign f_trade_flags      = i_win[199:192];
  assign f_bid_px           = {i_win[95:88], i_win[103:96], i_win[111:104], i_win[119:112]};
  assign f_ask_px           = {i_win[127:120], i_win[135:128], i_win[143:136], i_win[151:144]};
  assign f_bid_sz           = {i_win[159:152], i_win[167:160]};
  assign f_ask_sz           = {i_win[175:168], i_win[183:176]};
  assign f_session_state    = i_win[31:24];
  assign f_reason_code      = {i_win[39:32], i_win[47:40]};
  assign f_timestamp        = {i_win[55:48], i_win[63:56], i_win[71:64], i_win[79:72], i_win[87:80], i_win[95:88], i_win[103:96], i_win[111:104]};
  assign f_paired_qty       = {i_win[95:88], i_win[103:96], i_win[111:104], i_win[119:112], i_win[127:120], i_win[135:128], i_win[143:136], i_win[151:144]};
  assign f_imbalance_qty    = {i_win[159:152], i_win[167:160], i_win[175:168], i_win[183:176], i_win[191:184], i_win[199:192], i_win[207:200], i_win[215:208]};
  assign f_ref_px           = {i_win[223:216], i_win[231:224], i_win[239:232], i_win[247:240]};
  assign f_auction_type     = i_win[255:248];

  // --------------------------------------------------------- record pack ---
  assign o_rec[0    +: 16 ] = f_msg_len;
  assign o_rec[16   +: 8  ] = f_msg_type;
  assign o_rec[24   +: 64 ] = f_symbol;
  assign o_rec[88   +: 64 ] = f_price;
  assign o_rec[152  +: 32 ] = f_qty;
  assign o_rec[184  +: 8  ] = f_side;
  assign o_rec[192  +: 8  ] = f_trade_flags;
  assign o_rec[200  +: 32 ] = f_bid_px;
  assign o_rec[232  +: 32 ] = f_ask_px;
  assign o_rec[264  +: 16 ] = f_bid_sz;
  assign o_rec[280  +: 16 ] = f_ask_sz;
  assign o_rec[296  +: 8  ] = f_session_state;
  assign o_rec[304  +: 16 ] = f_reason_code;
  assign o_rec[320  +: 64 ] = f_timestamp;
  assign o_rec[384  +: 64 ] = f_paired_qty;
  assign o_rec[448  +: 64 ] = f_imbalance_qty;
  assign o_rec[512  +: 32 ] = f_ref_px;
  assign o_rec[544  +: 8  ] = f_auction_type;

endmodule

`default_nettype wire
