// -----------------------------------------------------------------------------
// GENERATED by wirespec 0.1.0 -- do not edit.
//
//   schema : simple_feed
//   DATA_W : 64
//
// Edit the template (wirespec/templates/hdr_parse_layered.sv.j2) and re-run:
//   wirespec gen --schema simple_feed --data-w 64 --out rtl/generated
// -----------------------------------------------------------------------------

// Header extraction for a layered protocol.
//
// Each layer is sliced from its own window of the accumulated header. A layer
// whose byte offset is known at elaboration gets a constant slice; one that sits
// behind a variable-length header gets a single run-time shift, shared by all of
// that layer's fields. That is rotate-then-slice at layer granularity: one
// shifter per layer, never one mux per field.
// See docs/decisions/0001-rotate-then-slice.md.
//
// The error precedence below mirrors wirespec/golden.py::_decode_layered
// exactly -- per layer, the fixed-size check, then the declared-length bounds,
// then the declared-length truncation check, then the next-layer selector.

`timescale 1ns / 1ps
`default_nettype none

module hdr_parse_simple_feed #(
  parameter int LEN_W     = pkg_wirespec::WS_LEN_W,
  parameter int HDR_BYTES = simple_feed_pkg::SIMPLE_FEED_HDR_BYTES,
  // Derived. Do not override.
  parameter int WIN_BITS  = HDR_BYTES * 8
) (
  input  wire                 clk,
  input  wire                 rst_n,

  // Live header window from hdr_accum: packet byte k at bits [8k+7:8k].
  input  wire [WIN_BITS-1:0]  i_win,
  input  wire [LEN_W-1:0]     i_have,
  input  wire                 i_done,

  // Combinational header length, for payload_window.
  output logic                o_strip_valid,
  output logic [LEN_W-1:0]    o_strip_bytes,

  // Record, registered, one pulse per packet.
  output logic                o_rec_valid,
  output logic [0:0]         o_layer_valid,
  output logic [2:0]          o_err,
  output logic [LEN_W-1:0]    o_hdr_bytes,

  output logic [31:0]         o_feed_hdr_session_id,
  output logic [63:0]         o_feed_hdr_seq_num,
  output logic [15:0]         o_feed_hdr_msg_count,
  output logic [15:0]         o_feed_hdr_reserved
);

  import pkg_wirespec::*;

  // --------------------------------------------------------------------------
  // layer 1/1: feed_hdr -- 16 bytes of fields
  // --------------------------------------------------------------------------
  logic [LEN_W-1:0]  off_feed_hdr;
  logic [LEN_W-1:0]  len_feed_hdr;
  logic [127:0] win_feed_hdr;

  assign off_feed_hdr = LEN_W'(0);

  assign win_feed_hdr = i_win[0 +: 128];

  logic [31:0]         feed_hdr_session_id   ;  // bits 0..31, 32b uint, big-endian
  logic [63:0]         feed_hdr_seq_num      ;  // bits 32..95, 64b uint, big-endian
  logic [15:0]         feed_hdr_msg_count    ;  // bits 96..111, 16b uint, big-endian
  logic [15:0]         feed_hdr_reserved     ;  // bits 112..127, 16b uint, big-endian

  assign feed_hdr_session_id    = {win_feed_hdr[7:0], win_feed_hdr[15:8], win_feed_hdr[23:16], win_feed_hdr[31:24]};
  assign feed_hdr_seq_num       = {win_feed_hdr[39:32], win_feed_hdr[47:40], win_feed_hdr[55:48], win_feed_hdr[63:56], win_feed_hdr[71:64], win_feed_hdr[79:72], win_feed_hdr[87:80], win_feed_hdr[95:88]};
  assign feed_hdr_msg_count     = {win_feed_hdr[103:96], win_feed_hdr[111:104]};
  assign feed_hdr_reserved      = {win_feed_hdr[119:112], win_feed_hdr[127:120]};

  assign len_feed_hdr = LEN_W'(16);

  // --------------------------------------------------------------------------
  // Chain walk
  // --------------------------------------------------------------------------
  logic active_feed_hdr;
  logic trunc_fix_feed_hdr;
  logic ok_feed_hdr;
  logic settled_feed_hdr;

  assign active_feed_hdr    = 1'b1;
  assign trunc_fix_feed_hdr = i_have < (off_feed_hdr + LEN_W'(16));
  assign ok_feed_hdr        = active_feed_hdr && !trunc_fix_feed_hdr;
  assign settled_feed_hdr   = ok_feed_hdr;

  // First failure along the active path wins, in the same order the model
  // applies its checks.
  logic [2:0] err;
  always_comb begin
    err = 3'(WS_OK);
    if (active_feed_hdr && trunc_fix_feed_hdr) begin
      err = 3'(WS_TRUNCATED);
    end
  end

  logic [0:0] layers_ok;
  assign layers_ok = { ok_feed_hdr };

  // A layer with no defined end has no defined payload: withholding
  // o_strip_valid makes payload_window report o_strip_err and emit nothing,
  // rather than shipping bytes measured from a fallback offset. (B005)
  always_comb begin
    o_strip_valid = settled_feed_hdr;
    if (settled_feed_hdr) begin
      o_strip_bytes = off_feed_hdr + len_feed_hdr;
    end else begin
      o_strip_bytes = LEN_W'(0);
    end
  end

  // --------------------------------------------------------------------------
  // Record
  // --------------------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (!rst_n) begin
      o_rec_valid <= 1'b0;
    end else begin
      o_rec_valid <= i_done;
      if (i_done) begin
        o_layer_valid <= layers_ok;
        o_err         <= err;
        o_hdr_bytes   <= o_strip_bytes;

        o_feed_hdr_session_id    <= feed_hdr_session_id;
        o_feed_hdr_seq_num       <= feed_hdr_seq_num;
        o_feed_hdr_msg_count     <= feed_hdr_msg_count;
        o_feed_hdr_reserved      <= feed_hdr_reserved;
      end
    end
  end

endmodule

`default_nettype wire
