// -----------------------------------------------------------------------------
// GENERATED by wirespec 0.1.0 -- do not edit.
//
//   schema : simple_feed
//   DATA_W : 64
//
// Edit the template (wirespec/templates/msg_check.sv.j2) and re-run:
//   wirespec gen --schema simple_feed --data-w 64 --out rtl/generated
// -----------------------------------------------------------------------------

// Type and size verdict from a message's prefix alone.
//
// `field_extract` answers the same two questions, but it needs the whole
// message window to do it. The framer's tail classifier has no whole message --
// it is looking at whatever is left after the last one, which may be a fragment
// of three bytes -- and it never emits a record, so extraction would be waste.
//
// It exists because a trailing fragment still has to be *classified*: "the type
// code is not one we know" and "there are not enough bytes" are different
// verdicts, and the golden model distinguishes them. Without it the framer
// could only ever say TRUNCATED, and a packet's verdict would depend on where
// its beat boundaries happened to fall (B009).
//
// The declared total is recomputed here rather than passed in, so the module
// depends on nothing but the 3 prefix bytes. That is one small adder
// duplicated; the alternative is an input port that is right by convention.
//
// Combinational, and small: one decode of the 8-bit type field plus
// 4 constant comparisons.

`timescale 1ns / 1ps
`default_nettype none

module msg_check_simple_feed #(
  parameter int PRE_BITS = 3 * 8,
  parameter int TOT_W    = 18
) (
  input  wire [PRE_BITS-1:0] i_pre,   // byte 0 = start of the message

  output wire                o_type_ok,
  output wire                o_size_ok
);

  // Total bytes the prefix declares: 2 big-endian length byte(s) at offset
  // 0, plus 2 for what the length does not cover.
  logic [TOT_W-1:0] total;
  always_comb begin
    total = TOT_W'(2);
    total = total + (TOT_W'(i_pre[0 +: 8]) << 8);
    total = total + (TOT_W'(i_pre[8 +: 8]) << 0);
  end

  wire [7:0] mtype;
  assign mtype = i_pre[23:16];

  wire is_trade        = (mtype == 8'h01);
  wire is_quote        = (mtype == 8'h02);
  wire is_status       = (mtype == 8'h03);
  wire is_imbalance    = (mtype == 8'h04);

  assign o_type_ok = is_trade || is_quote || is_status || is_imbalance;

  assign o_size_ok = (is_trade && (total == TOT_W'(25))) ||
                     (is_quote && (total == TOT_W'(23))) ||
                     (is_status && (total == TOT_W'(14))) ||
                     (is_imbalance && (total == TOT_W'(32)));

endmodule

`default_nettype wire
