// -----------------------------------------------------------------------------
// GENERATED by wirespec 0.1.0 -- do not edit.
//
//   schema : simple_feed
//   DATA_W : 64
//
// Edit the template (wirespec/templates/parser_top_framed.sv.j2) and re-run:
//   wirespec gen --schema simple_feed --data-w 64 --out rtl/generated
// -----------------------------------------------------------------------------

// Top level for a framed protocol: AXI4-Stream in, one packet-header record and
// up to SLOTS message records per cycle out, plus stream counters.
//
//   pkt_align -> hdr_accum -> hdr_parse (the fixed packet header)
//                          -> payload_window (strip the header)
//                          -> msg_stitch (carry partial messages across beats)
//                          -> msg_framer (SLOTS x msg_rotate, boundary chain)
//                          -> field_extract x SLOTS (static slices)
//
// s_axis_tready is tied high; nothing here can stall.

`timescale 1ns / 1ps
`default_nettype none

module parser_top_simple_feed #(
  parameter int DATA_W = 64,
  parameter int LEN_W  = pkg_wirespec::WS_LEN_W,
  parameter int CNT_W  = 32,
  // Derived. Do not override.
  parameter int KEEP_W = DATA_W / 8,
  parameter int BCNT_W = $clog2(DATA_W / 8 + 1),
  parameter int SLOTS  = (DATA_W / 8 + 14 - 1) / 14,
  parameter int REC_W  = simple_feed_pkg::SIMPLE_FEED_REC_W
) (
  input  wire                clk,
  input  wire                rst_n,

  input  wire                s_axis_tvalid,
  output wire                s_axis_tready,
  input  wire [DATA_W-1:0]   s_axis_tdata,
  input  wire [KEEP_W-1:0]   s_axis_tkeep,
  input  wire                s_axis_tlast,

  // Packet header record, one pulse per packet.
  output wire                o_rec_valid,
  output wire [2:0]          o_hdr_err,
  output wire [31:0]          o_feed_hdr_session_id,
  output wire [63:0]          o_feed_hdr_seq_num,
  output wire [15:0]          o_feed_hdr_msg_count,
  output wire [15:0]          o_feed_hdr_reserved,

  // Message records. Up to SLOTS in one cycle; unpack o_msg_data with the
  // REC_*_LSB constants in simple_feed_pkg.
  output wire [SLOTS-1:0]        o_msg_valid,
  output wire [SLOTS*REC_W-1:0]  o_msg_data,

  // Per-packet verdict, after every message of that packet.
  output logic               o_pkt_done,
  output logic [2:0]         o_pkt_err,
  output logic [15:0]        o_pkt_msgs,

  // Counters.
  output wire [CNT_W-1:0]    o_stat_packets,
  output wire [CNT_W-1:0]    o_stat_messages,
  output wire [CNT_W-1:0]    o_stat_seq_gaps,
  output wire [CNT_W-1:0]    o_stat_malformed,

  output wire                o_keep_err,
  output wire                o_overflow
);

  localparam int HDR_BYTES = simple_feed_pkg::SIMPLE_FEED_HDR_BYTES;
  localparam int WIN_BITS  = HDR_BYTES * 8;
  localparam int ACC_BEATS = (HDR_BYTES + KEEP_W - 1) / KEEP_W;
  localparam int ACC_BITS  = ACC_BEATS * KEEP_W * 8;
  localparam int MSG_MAX   = 32;
  localparam int MSG_MIN   = 14;
  localparam int BUF_BYTES = MSG_MAX - 1 + KEEP_W;
  localparam int OFF_W     = $clog2(BUF_BYTES + 1);
  localparam int MSG_BITS  = MSG_MAX * 8;
  localparam int TOT_W     = 18;

  assign s_axis_tready = 1'b1;

  // ---------------------------------------------------------- alignment ----
  logic              al_valid;
  logic [DATA_W-1:0] al_data;
  logic [KEEP_W-1:0] al_keep;
  logic              al_sof;
  logic              al_eof;
  logic [BCNT_W-1:0] al_bytes;
  logic [LEN_W-1:0]  al_offset;
  logic [LEN_W-1:0]  al_pkt_bytes;

  pkt_align #(.DATA_W(DATA_W), .LEN_W(LEN_W)) u_align (
    .clk(clk), .rst_n(rst_n),
    .s_tvalid(s_axis_tvalid), .s_tdata(s_axis_tdata),
    .s_tkeep(s_axis_tkeep), .s_tlast(s_axis_tlast),
    .o_valid(al_valid), .o_data(al_data), .o_keep(al_keep),
    .o_sof(al_sof), .o_eof(al_eof), .o_bytes(al_bytes),
    .o_offset(al_offset), .o_pkt_bytes(al_pkt_bytes), .o_keep_err(o_keep_err)
  );

  // ---------------------------------------------------- header gathering ----
  logic [ACC_BITS-1:0] acc_win;
  logic [LEN_W-1:0]    acc_have;
  logic                acc_done;
  logic                acc_short;

  hdr_accum #(.DATA_W(DATA_W), .HDR_BYTES(HDR_BYTES), .LEN_W(LEN_W)) u_accum (
    .clk(clk), .rst_n(rst_n),
    .i_valid(al_valid), .i_data(al_data), .i_sof(al_sof), .i_eof(al_eof),
    .i_bytes(al_bytes), .i_offset(al_offset),
    .o_win(acc_win), .o_have(acc_have), .o_done(acc_done), .o_short(acc_short)
  );

  logic             strip_valid;
  logic [LEN_W-1:0] strip_bytes;
  logic [0:0]       hdr_layer_ok;
  logic [LEN_W-1:0] hdr_bytes;

  hdr_parse_simple_feed #(.LEN_W(LEN_W), .HDR_BYTES(HDR_BYTES)) u_parse (
    .clk(clk), .rst_n(rst_n),
    .i_win(acc_win[WIN_BITS-1:0]), .i_have(acc_have), .i_done(acc_done),
    .o_strip_valid(strip_valid), .o_strip_bytes(strip_bytes),
    .o_rec_valid(o_rec_valid), .o_layer_valid(hdr_layer_ok),
    .o_err(o_hdr_err), .o_hdr_bytes(hdr_bytes),
    .o_feed_hdr_session_id(o_feed_hdr_session_id),
    .o_feed_hdr_seq_num  (o_feed_hdr_seq_num),
    .o_feed_hdr_msg_count(o_feed_hdr_msg_count),
    .o_feed_hdr_reserved (o_feed_hdr_reserved)
  );

  // ------------------------------------------------------------ payload ----
  logic              pay_valid;
  logic [DATA_W-1:0] pay_data;
  logic [KEEP_W-1:0] pay_keep;
  logic              pay_sof;
  logic              pay_eof;
  logic [BCNT_W-1:0] pay_bytes;
  logic [LEN_W-1:0]  pay_offset;
  logic              pay_empty;
  logic              pay_strip_err;

  payload_window #(.DATA_W(DATA_W), .LEN_W(LEN_W)) u_payload (
    .clk(clk), .rst_n(rst_n),
    .i_valid(al_valid), .i_data(al_data), .i_sof(al_sof), .i_eof(al_eof),
    .i_bytes(al_bytes), .i_offset(al_offset),
    .i_strip_valid(strip_valid), .i_strip_bytes(strip_bytes),
    .o_valid(pay_valid), .o_data(pay_data), .o_keep(pay_keep),
    .o_sof(pay_sof), .o_eof(pay_eof), .o_bytes(pay_bytes),
    .o_offset(pay_offset), .o_empty(pay_empty), .o_strip_err(pay_strip_err)
  );

  // ------------------------------------------------------------- stitch ----
  logic [BUF_BYTES*8-1:0] stitch_win;
  logic [OFF_W-1:0]       stitch_nvalid;
  logic                   stitch_start;
  logic                   stitch_last;
  logic [OFF_W-1:0]       consume;

  msg_stitch #(.DATA_W(DATA_W), .MSG_MAX(MSG_MAX)) u_stitch (
    .clk(clk), .rst_n(rst_n),
    .i_valid(pay_valid), .i_data(pay_data), .i_sof(pay_sof), .i_eof(pay_eof),
    .i_bytes(pay_bytes), .i_empty(pay_empty), .i_consume(consume),
    .o_win(stitch_win), .o_nvalid(stitch_nvalid),
    .o_pkt_start(stitch_start), .o_pkt_last(stitch_last), .o_overflow(o_overflow)
  );

  // ------------------------------------------------------------- framer ----
  logic [SLOTS*MSG_BITS-1:0] slot_win;
  logic [SLOTS*TOT_W-1:0]    slot_total;
  logic [SLOTS-1:0]          slot_type_ok;
  logic [SLOTS-1:0]          slot_size_ok;
  logic                      fr_done;
  logic [2:0]                fr_err;
  logic [15:0]               fr_msgs;
  logic [SLOTS-1:0]          fr_slot_valid;
  logic [SLOTS*REC_W-1:0]    fr_rec;
  logic                      pkt_done_any;
  logic [2:0]                pkt_err_any;
  logic [15:0]               declared_msgs;

  msg_framer #(
    .DATA_W(DATA_W), .MSG_MAX(MSG_MAX), .MSG_MIN(MSG_MIN),
    .LEN_OFF(0), .LEN_BYTES(2),
    .LEN_ADD(2), .PREFIX(3), .CNT_W(16)
  ) u_framer (
    .clk(clk), .rst_n(rst_n),
    .i_win(stitch_win), .i_nvalid(stitch_nvalid),
    .i_pkt_start(stitch_start), .i_pkt_last(stitch_last),
    .i_type_ok(slot_type_ok), .i_size_ok(slot_size_ok),
    .o_win(slot_win), .o_total(slot_total),
    .o_slot_valid(fr_slot_valid), .o_consume(consume),
    .o_pkt_done(fr_done), .o_pkt_err(fr_err), .o_pkt_msgs(fr_msgs)
  );

  // One extractor per slot. Its type/size verdicts feed back into the framer,
  // which is not a loop: message boundaries come from the length prefix alone,
  // so nothing the extractor says can move them.
  logic [SLOTS*8-1:0] slot_type;

  genvar s;
  generate
    for (s = 0; s < SLOTS; s++) begin : g_extract
      field_extract_simple_feed #(
        .MSG_BITS(MSG_BITS), .TOT_W(TOT_W), .REC_W(REC_W)
      ) u_extract (
        .i_win    (slot_win[s*MSG_BITS +: MSG_BITS]),
        .i_total  (slot_total[s*TOT_W +: TOT_W]),
        .o_type_ok(slot_type_ok[s]),
        .o_size_ok(slot_size_ok[s]),
        .o_type   (slot_type[s*8 +: 8]),
        .o_rec    (fr_rec[s*REC_W +: REC_W])
      );
    end
  endgenerate

  // The message bus is registered so that it sits on the same pipeline stage as
  // o_pkt_done. Left combinational, a packet's first message could be presented
  // in the very cycle the *previous* packet's verdict appears -- which happens
  // as soon as one beat is wide enough to hold a whole message, at DATA_W=128
  // and above -- and a consumer would have no way to tell which packet it
  // belonged to. (docs/bugs-found.md B006)
  logic [SLOTS-1:0]       msg_valid_q;
  logic [SLOTS*REC_W-1:0] msg_data_q;

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      msg_valid_q <= '0;
    end else begin
      msg_valid_q <= fr_slot_valid;
      if (|fr_slot_valid) begin
        msg_data_q <= fr_rec;
      end
    end
  end

  assign o_msg_valid = msg_valid_q;
  assign o_msg_data  = msg_data_q;

  // ------------------------------------------------- packet-header queue ----
  // A packet's header record is produced from its first bytes, but its message
  // count can only be checked once its last message is decoded -- and with
  // back-to-back packets the next header arrives first. Four entries is more
  // than the two-packet skew needs.
  localparam int META_DEPTH = 4;
  localparam int META_W     = 16 + 64;

  logic [META_W-1:0] meta_q [META_DEPTH];
  logic [1:0]        meta_wr;
  logic [1:0]        meta_rd;
  logic [META_W-1:0] meta_head;

  assign meta_head = meta_q[meta_rd];

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      meta_wr <= '0;
      meta_rd <= '0;
    end else begin
      if (o_rec_valid) begin
        meta_q[meta_wr] <= { o_feed_hdr_seq_num, o_feed_hdr_msg_count };
        meta_wr <= meta_wr + 2'd1;
      end
      if (pkt_done_any) begin
        meta_rd <= meta_rd + 2'd1;
      end
    end
  end

  // ------------------------------------------------------- packet verdict ---
  // Two ways a packet finishes: through the framer, or -- when the header was
  // too short to even locate the payload -- straight off payload_window's
  // strip error. Every packet reports exactly once either way.
  assign pkt_done_any  = fr_done || pay_strip_err;
  assign declared_msgs = meta_head[15:0];

  always_comb begin
    if (pay_strip_err) begin
      pkt_err_any = 3'(pkg_wirespec::WS_TRUNCATED);
    end else if (fr_err != 3'(pkg_wirespec::WS_OK)) begin
      pkt_err_any = fr_err;
    end else if (fr_msgs != declared_msgs) begin
      pkt_err_any = 3'(pkg_wirespec::WS_COUNT_MISMATCH);
    end else begin
      pkt_err_any = 3'(pkg_wirespec::WS_OK);
    end
  end

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      o_pkt_done <= 1'b0;
      o_pkt_err  <= 3'(pkg_wirespec::WS_OK);
      o_pkt_msgs <= '0;
    end else begin
      o_pkt_done <= pkt_done_any;
      o_pkt_err  <= pkt_err_any;
      o_pkt_msgs <= pay_strip_err ? 16'd0 : fr_msgs;
    end
  end

  // -------------------------------------------------------------- stats ----
  stats #(.CNT_W(CNT_W), .SEQ_W(64), .MSG_W(16)) u_stats (
    .clk(clk), .rst_n(rst_n), .clear(1'b0),
    .i_pkt_done (pkt_done_any),
    .i_pkt_bad  (pkt_err_any != 3'(pkg_wirespec::WS_OK)),
    .i_pkt_msgs (pay_strip_err ? 16'd0 : fr_msgs),
    .i_seq_valid(1'b1),
    .i_seq      (meta_head[META_W-1:16]),
    .o_packets  (o_stat_packets),
    .o_messages (o_stat_messages),
    .o_seq_gaps (o_stat_seq_gaps),
    .o_malformed(o_stat_malformed)
  );

  // Diagnostics not carried on any record bus. hdr_accum rounds its window up
  // to a whole number of beats, and the padding past the header is never read --
  // but only when there is padding, which depends on DATA_W.
  logic acc_pad;
  generate
    if (ACC_BITS > WIN_BITS) begin : g_pad
      assign acc_pad = &acc_win[ACC_BITS-1:WIN_BITS];
    end else begin : g_nopad
      assign acc_pad = 1'b0;
    end
  endgenerate

  logic unused_ok;
  assign unused_ok = &{1'b0, acc_short, al_keep, al_pkt_bytes, hdr_layer_ok,
                       hdr_bytes, pay_keep, pay_offset, slot_type, acc_pad};

endmodule

`default_nettype wire
