// -----------------------------------------------------------------------------
// GENERATED by wirespec 0.1.0 -- do not edit.
//
//   schema : eth_ipv4_udp
//   DATA_W : 64
//
// Edit the template (wirespec/templates/parser_top_layered.sv.j2) and re-run:
//   wirespec gen --schema eth_ipv4_udp --data-w 64 --out rtl/generated
// -----------------------------------------------------------------------------

// Top level: AXI4-Stream in, one header record per packet plus a lane-0-aligned
// payload stream out.
//
// Two promises, both asserted continuously by the testbench:
//   1. s_axis_tready is tied high. The parser never backpressures its ingress.
//   2. Every output lands a fixed number of cycles behind the ingress beat that
//      caused it. See docs/decisions/0003-no-backpressure-fixed-schedule.md for
//      the one structural exception, the payload tail beat.
//
// Both fall out of the structure: there is no handshake anywhere inside, and no
// stage's depth depends on the data.

`timescale 1ns / 1ps
`default_nettype none

module parser_top_eth_ipv4_udp #(
  parameter int DATA_W = 64,
  parameter int LEN_W  = pkg_wirespec::WS_LEN_W,
  // Derived. Do not override.
  parameter int KEEP_W = DATA_W / 8,
  parameter int BCNT_W = $clog2(DATA_W / 8 + 1)
) (
  input  wire                clk,
  input  wire                rst_n,

  input  wire                s_axis_tvalid,
  output wire                s_axis_tready,
  input  wire [DATA_W-1:0]   s_axis_tdata,
  input  wire [KEEP_W-1:0]   s_axis_tkeep,
  input  wire                s_axis_tlast,

  // Payload stream. Valid-only: nothing downstream may stall the parser.
  output wire                m_pay_valid,
  output wire [DATA_W-1:0]   m_pay_data,
  output wire [KEEP_W-1:0]   m_pay_keep,
  output wire                m_pay_sof,
  output wire                m_pay_eof,
  output wire [BCNT_W-1:0]   m_pay_bytes,
  output wire [LEN_W-1:0]    m_pay_offset,
  output wire                m_pay_empty,

  // One record per packet.
  output wire                o_rec_valid,
  output wire [2:0]          o_layer_valid,
  output wire [2:0]          o_err,
  output wire [LEN_W-1:0]    o_hdr_bytes,
  output wire                o_keep_err,
  output wire                o_strip_err,

  output wire [47:0]          o_eth_dst_mac,
  output wire [47:0]          o_eth_src_mac,
  output wire [15:0]          o_eth_ethertype,
  output wire [3:0]           o_ipv4_version,
  output wire [3:0]           o_ipv4_ihl,
  output wire [5:0]           o_ipv4_dscp,
  output wire [1:0]           o_ipv4_ecn,
  output wire [15:0]          o_ipv4_total_length,
  output wire [15:0]          o_ipv4_identification,
  output wire [2:0]           o_ipv4_flags,
  output wire [12:0]          o_ipv4_frag_offset,
  output wire [7:0]           o_ipv4_ttl,
  output wire [7:0]           o_ipv4_protocol,
  output wire [15:0]          o_ipv4_hdr_checksum,
  output wire [31:0]          o_ipv4_src_ip,
  output wire [31:0]          o_ipv4_dst_ip,
  output wire [15:0]          o_udp_src_port,
  output wire [15:0]          o_udp_dst_port,
  output wire [15:0]          o_udp_length,
  output wire [15:0]          o_udp_checksum
);

  localparam int HDR_BYTES = eth_ipv4_udp_pkg::ETH_IPV4_UDP_HDR_BYTES;
  localparam int WIN_BITS  = HDR_BYTES * 8;
  localparam int ACC_BEATS = (HDR_BYTES + KEEP_W - 1) / KEEP_W;
  localparam int ACC_BITS  = ACC_BEATS * KEEP_W * 8;

  assign s_axis_tready = 1'b1;

  // ---------------------------------------------------------- alignment ----
  logic              al_valid;
  logic [DATA_W-1:0] al_data;
  logic [KEEP_W-1:0] al_keep;
  logic              al_sof;
  logic              al_eof;
  logic [BCNT_W-1:0] al_bytes;
  logic [LEN_W-1:0]  al_offset;
  logic [LEN_W-1:0]  al_pkt_bytes;
  logic                 nx_sof;
  logic [BCNT_W-1:0]    nx_bytes;
  logic [LEN_W-1:0]     nx_pkt_bytes;

  pkt_align #(
    .DATA_W(DATA_W),
    .LEN_W (LEN_W)
  ) u_align (
    .clk        (clk),
    .rst_n      (rst_n),
    .s_tvalid   (s_axis_tvalid),
    .s_tdata    (s_axis_tdata),
    .s_tkeep    (s_axis_tkeep),
    .s_tlast    (s_axis_tlast),
    .o_valid    (al_valid),
    .o_data     (al_data),
    .o_keep     (al_keep),
    .o_sof      (al_sof),
    .o_eof      (al_eof),
    .o_bytes    (al_bytes),
    .o_offset   (al_offset),
    .o_pkt_bytes (al_pkt_bytes),
    .o_keep_err  (o_keep_err),
    .nx_sof      (nx_sof),
    .nx_bytes    (nx_bytes),
    .nx_pkt_bytes(nx_pkt_bytes)
  );

  // ---------------------------------------------------- header gathering ----
  logic [ACC_BITS-1:0] acc_win;
  logic [LEN_W-1:0]    acc_have;
  logic [HDR_BYTES:0]  acc_have_ge;
  logic                acc_done;
  logic                acc_short;

  hdr_accum #(
    .DATA_W   (DATA_W),
    .HDR_BYTES(HDR_BYTES),
    .LEN_W    (LEN_W)
  ) u_accum (
    .clk     (clk),
    .rst_n   (rst_n),
    .s_valid     (s_axis_tvalid),
    .s_data      (s_axis_tdata),
    .s_last      (s_axis_tlast),
    .nx_sof      (nx_sof),
    .nx_bytes    (nx_bytes),
    .nx_pkt_bytes(nx_pkt_bytes),
    .o_win       (acc_win),
    .o_have      (acc_have),
    .o_have_ge   (acc_have_ge),
    .o_done      (acc_done),
    .o_short     (acc_short)
  );

  // ------------------------------------------------------------- parse -----
  logic             strip_valid;
  logic [LEN_W-1:0] strip_bytes;

  hdr_parse_eth_ipv4_udp #(
    .LEN_W    (LEN_W),
    .HDR_BYTES(HDR_BYTES)
  ) u_parse (
    .clk          (clk),
    .rst_n        (rst_n),
    .i_win        (acc_win[WIN_BITS-1:0]),
    .i_have_ge    (acc_have_ge),
    .i_done       (acc_done),
    .o_strip_valid(strip_valid),
    .o_strip_bytes(strip_bytes),
    .o_rec_valid  (o_rec_valid),
    .o_layer_valid(o_layer_valid),
    .o_err        (o_err),
    .o_hdr_bytes  (o_hdr_bytes),
    .o_eth_dst_mac         (o_eth_dst_mac),
    .o_eth_src_mac         (o_eth_src_mac),
    .o_eth_ethertype       (o_eth_ethertype),
    .o_ipv4_version        (o_ipv4_version),
    .o_ipv4_ihl            (o_ipv4_ihl),
    .o_ipv4_dscp           (o_ipv4_dscp),
    .o_ipv4_ecn            (o_ipv4_ecn),
    .o_ipv4_total_length   (o_ipv4_total_length),
    .o_ipv4_identification (o_ipv4_identification),
    .o_ipv4_flags          (o_ipv4_flags),
    .o_ipv4_frag_offset    (o_ipv4_frag_offset),
    .o_ipv4_ttl            (o_ipv4_ttl),
    .o_ipv4_protocol       (o_ipv4_protocol),
    .o_ipv4_hdr_checksum   (o_ipv4_hdr_checksum),
    .o_ipv4_src_ip         (o_ipv4_src_ip),
    .o_ipv4_dst_ip         (o_ipv4_dst_ip),
    .o_udp_src_port        (o_udp_src_port),
    .o_udp_dst_port        (o_udp_dst_port),
    .o_udp_length          (o_udp_length),
    .o_udp_checksum        (o_udp_checksum)
  );

  // ------------------------------------------------------------ payload ----
  payload_window #(
    .DATA_W(DATA_W),
    .LEN_W (LEN_W)
  ) u_payload (
    .clk          (clk),
    .rst_n        (rst_n),
    .i_valid      (al_valid),
    .i_data       (al_data),
    .i_sof        (al_sof),
    .i_eof        (al_eof),
    .i_bytes      (al_bytes),
    .i_offset     (al_offset),
    .i_strip_valid(strip_valid),
    .i_strip_bytes(strip_bytes),
    .o_valid      (m_pay_valid),
    .o_data       (m_pay_data),
    .o_keep       (m_pay_keep),
    .o_sof        (m_pay_sof),
    .o_eof        (m_pay_eof),
    .o_bytes      (m_pay_bytes),
    .o_offset     (m_pay_offset),
    .o_empty      (m_pay_empty),
    .o_strip_err  (o_strip_err)
  );

  // Diagnostics the record does not carry: truncation is already implied by
  // acc_have at acc_done, and the keep mask is validated by pkt_align. Tie them
  // off rather than leaving dangling nets.
  logic acc_pad;
  generate
    if (ACC_BITS > WIN_BITS) begin : g_pad
      assign acc_pad = &acc_win[ACC_BITS-1:WIN_BITS];
    end else begin : g_nopad
      assign acc_pad = 1'b0;
    end
  endgenerate

  logic unused_ok;
  assign unused_ok = &{1'b0, acc_short, al_keep, al_pkt_bytes, acc_have, acc_pad};

endmodule

`default_nettype wire
