// -----------------------------------------------------------------------------
// GENERATED by wirespec 0.1.0 -- do not edit.
//
//   schema : simple_feed
//   DATA_W : 64
//
// Edit the template (wirespec/templates/proto_pkg.sv.j2) and re-run:
//   wirespec gen --schema simple_feed --data-w 64 --out rtl/generated
// -----------------------------------------------------------------------------

`timescale 1ns / 1ps
`default_nettype none

package simple_feed_pkg;

  // Worst-case bytes consumed before the payload begins: the longest
  // root-to-leaf path through the layer chain.
  //   feed_hdr     offset 0                        16 B
  localparam int SIMPLE_FEED_HDR_BYTES = 16;
  localparam int SIMPLE_FEED_LAYERS    = 1;

  localparam int FEED_HDR_BYTES = 16;

  // Bit position of each layer in the record bus's o_layer_valid.
  typedef enum logic [0:0] {
    LAYER_FEED_HDR = 1'd0
  } simple_feed_layer_e;

  typedef enum logic [7:0] {
    SIDE_E_BUY = 8'h42,
    SIDE_E_SELL = 8'h53
  } side_e;

  typedef enum logic [7:0] {
    SESSION_STATE_E_PRE_OPEN = 8'h00,
    SESSION_STATE_E_OPEN = 8'h01,
    SESSION_STATE_E_HALTED = 8'h02,
    SESSION_STATE_E_CLOSED = 8'h03
  } session_state_e;

  typedef enum logic [7:0] {
    AUCTION_E_NONE = 8'h00,
    AUCTION_E_OPENING = 8'h01,
    AUCTION_E_CLOSING = 8'h02,
    AUCTION_E_HALT_RESUME = 8'h03
  } auction_e;

  // Messages. Sized so the framer never falls behind: MSG_MAX-1 bytes can be
  // left over and one beat adds KEEP_W more, so at most SLOTS messages can
  // complete in a cycle.
  localparam int SIMPLE_FEED_MSG_MAX   = 32;
  localparam int SIMPLE_FEED_MSG_MIN   = 14;
  localparam int SIMPLE_FEED_PREFIX    = 3;
  localparam int SIMPLE_FEED_LEN_OFF   = 0;
  localparam int SIMPLE_FEED_LEN_BYTES = 2;
  localparam int SIMPLE_FEED_LEN_ADD   = 2;
  localparam int SIMPLE_FEED_REC_W     = 552;

  typedef enum logic [7:0] {
    MSG_TRADE = 8'h01,
    MSG_QUOTE = 8'h02,
    MSG_STATUS = 8'h03,
    MSG_IMBALANCE = 8'h04
  } simple_feed_msg_e;

  localparam int MSG_TRADE_BYTES              = 25;
  localparam int MSG_QUOTE_BYTES              = 23;
  localparam int MSG_STATUS_BYTES             = 14;
  localparam int MSG_IMBALANCE_BYTES          = 32;

  // Bit position of each field in the message record bus. The testbench unpacks
  // o_msg_data with these, so unlike the layer offsets below they are load
  // bearing.
  localparam int REC_MSG_LEN_LSB              = 0   ;
  localparam int REC_MSG_LEN_W                = 16  ;
  localparam int REC_MSG_TYPE_LSB             = 16  ;
  localparam int REC_MSG_TYPE_W               = 8   ;
  localparam int REC_SYMBOL_LSB               = 24  ;
  localparam int REC_SYMBOL_W                 = 64  ;
  localparam int REC_PRICE_LSB                = 88  ;
  localparam int REC_PRICE_W                  = 64  ;
  localparam int REC_QTY_LSB                  = 152 ;
  localparam int REC_QTY_W                    = 32  ;
  localparam int REC_SIDE_LSB                 = 184 ;
  localparam int REC_SIDE_W                   = 8   ;
  localparam int REC_TRADE_FLAGS_LSB          = 192 ;
  localparam int REC_TRADE_FLAGS_W            = 8   ;
  localparam int REC_BID_PX_LSB               = 200 ;
  localparam int REC_BID_PX_W                 = 32  ;
  localparam int REC_ASK_PX_LSB               = 232 ;
  localparam int REC_ASK_PX_W                 = 32  ;
  localparam int REC_BID_SZ_LSB               = 264 ;
  localparam int REC_BID_SZ_W                 = 16  ;
  localparam int REC_ASK_SZ_LSB               = 280 ;
  localparam int REC_ASK_SZ_W                 = 16  ;
  localparam int REC_SESSION_STATE_LSB        = 296 ;
  localparam int REC_SESSION_STATE_W          = 8   ;
  localparam int REC_REASON_CODE_LSB          = 304 ;
  localparam int REC_REASON_CODE_W            = 16  ;
  localparam int REC_TIMESTAMP_LSB            = 320 ;
  localparam int REC_TIMESTAMP_W              = 64  ;
  localparam int REC_PAIRED_QTY_LSB           = 384 ;
  localparam int REC_PAIRED_QTY_W             = 64  ;
  localparam int REC_IMBALANCE_QTY_LSB        = 448 ;
  localparam int REC_IMBALANCE_QTY_W          = 64  ;
  localparam int REC_REF_PX_LSB               = 512 ;
  localparam int REC_REF_PX_W                 = 32  ;
  localparam int REC_AUCTION_TYPE_LSB         = 544 ;
  localparam int REC_AUCTION_TYPE_W           = 8   ;

  // Field offsets, in bits from the start of the layer that carries them.
  // Emitted for consumers of the record bus; this module does not read them,
  // hence the narrow waiver.
  /* verilator lint_off UNUSEDPARAM */
  localparam int FEED_HDR_SESSION_ID_OFF            = 0   ;
  localparam int FEED_HDR_SESSION_ID_W              = 32  ;
  localparam int FEED_HDR_SEQ_NUM_OFF               = 32  ;
  localparam int FEED_HDR_SEQ_NUM_W                 = 64  ;
  localparam int FEED_HDR_MSG_COUNT_OFF             = 96  ;
  localparam int FEED_HDR_MSG_COUNT_W               = 16  ;
  localparam int FEED_HDR_RESERVED_OFF              = 112 ;
  localparam int FEED_HDR_RESERVED_W                = 16  ;
  /* verilator lint_on UNUSEDPARAM */

endpackage

`default_nettype wire
